name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.5+3
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3 # Added for state management testing
  equatable: ^2.0.5 # For value comparison in tests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test: ^1.2.0 # For integration tests
  mockito: ^5.4.2 # For mocking dependencies
  bloc_test: ^9.1.4 # For bloc testing
  test: ^1.24.0 # Core test package
  flutter_driver:
    sdk: flutter # For driver tests
  build_runner: ^2.4.6 # For code generation

flutter:
  uses-material-design: true