name: frontend
description: "A Flutter project with Dart 3.8.1+ compatibility"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'  # Matches Flutter master channel

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4    # Updated for Flutter 3.13.0+ compatibility
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test: ^2.0.0  # Updated version for Flutter 3.13.0+
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  test: ^1.24.0
  flutter_driver: ^2.3.0    # Updated version
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
