version: '3.9'

services:
  db:
    image: postgres:16
    container_name: innosync-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: innosync
      POSTGRES_PASSWORD: innosyncpass
      POSTGRES_DB: innosync
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: innosync-backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: innosync
      DB_PASSWORD: innosyncpass
      DB_NAME: innosync
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/root/uploads
      - ./backend/config.yaml:/root/config.yaml:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: innosync-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: