server:
  port: 3000
  host: "0.0.0.0"
  mode: "debug"
  timeout: 30

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "innosync"
  sslmode: "disable"

jwt:
  secret_key: "your-secret-key-change-this-in-production"
  access_token_ttl: "15m"
  refresh_token_ttl: "168h" # 7 days

upload:
  max_file_size: 10485760 # 10MB
  upload_dir: "uploads"
  allowed_extensions:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".pdf"
    - ".doc"
    - ".docx"