name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        channel: 'stable'
    
    - name: Change to frontend directory
      run: cd frontend
    
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./frontend
    
    - name: Build APK
      run: flutter build apk --release
      working-directory: ./frontend
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: frontend/build/app/outputs/flutter-apk/app-release.apk 